language: php
php:
  - '7.1'
install: composer install --no-interaction
script:
  - php console.php daily --team=fz
  - git add data
  - git commit --allow-empty -m "Data changes" -- data
  - git remote set-url origin https://kevbaldwyn:$GITHUB_TOKEN@github.com/funeralzone/rota-planner.git
  - git push origin HEAD:master
branches:
  only: master
cache:
  directories:
  - vendor
  - $HOME/.cache/composer